spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phone-shop?allowMultiQueries=true&characterEncoding=utf8&useUnicode=true
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper‐locations: classpath:mybatis/*.xml

server:
  port: 8082
  tomcat:
    max-connections: 20000
    max-threads: 50
    min-spare-threads: 20
    accept-count: 1000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
